### ISSUE TITLE
Crash on MSBuild

### ISSUE THREAD

**Issue by yeeezsh** [codeleague/codecoach#122]
log

```
[10:55:58]Collecting changes in 2 VCS roots (14s)
[10:59:34]The build is removed from the queue to be prepared for the start
[10:59:34]Starting the build on the agent "hk-unix-1630380965918"
[10:59:34]Updating tools for build
[10:59:34]Clearing temporary directory: /opt/buildagent/temp/buildTmp
[10:59:34]Publishing internal artifacts (3s)
[10:59:34]Checkout directory: /opt/buildagent/work/cb585e686fd79a0a
[10:59:34]Resolving artifact dependencies
[10:59:34]Step 1/2: Run (Command Line) (19s)
[10:59:34][Step 1/2] Swabra
[10:59:34][Step 1/2] Starting: /opt/buildagent/temp/agentTmp/custom_script4594896988933018394
[10:59:34][Step 1/2] in directory: /opt/buildagent/work/cb585e686fd79a0a
[10:59:34][Step 1/2] PR 420
[10:59:34][Step 1/2] MSBuild execution path C:/buildagent/work/1c22f4d3d9030336
[10:59:34][Step 1/2] ESLint execution path C:/buildagent/work/1c22f4d3d9030336
[10:59:34][Step 1/2] Unable to find image 'reg-hk.agodadev.io/library/node:14-slim' locally
[10:59:34][Step 1/2] 14-slim: Pulling from library/node
[10:59:34][Step 1/2] babf97a3f00a: Pulling fs layer
[10:59:34][Step 1/2] d81eb1809d95: Pulling fs layer
[10:59:34][Step 1/2] 1d14a5c3c182: Pulling fs layer
[10:59:34][Step 1/2] 21d157458a67: Pulling fs layer
[10:59:34][Step 1/2] b358ef6b56c5: Pulling fs layer
[10:59:34][Step 1/2] 21d157458a67: Waiting
[10:59:34][Step 1/2] b358ef6b56c5: Waiting
[10:59:34][Step 1/2] d81eb1809d95: Verifying Checksum
[10:59:34][Step 1/2] d81eb1809d95: Download complete
[10:59:35][Step 1/2] 21d157458a67: Verifying Checksum
[10:59:35][Step 1/2] 21d157458a67: Download complete
[10:59:35][Step 1/2] b358ef6b56c5: Download complete
[10:59:35][Step 1/2] babf97a3f00a: Download complete
[10:59:35][Step 1/2] 1d14a5c3c182: Verifying Checksum
[10:59:35][Step 1/2] 1d14a5c3c182: Download complete
[10:59:36][Step 1/2] babf97a3f00a: Pull complete
[10:59:36][Step 1/2] d81eb1809d95: Pull complete
[10:59:39][Step 1/2] 1d14a5c3c182: Pull complete
[10:59:39][Step 1/2] 21d157458a67: Pull complete
[10:59:39][Step 1/2] b358ef6b56c5: Pull complete
[10:59:39][Step 1/2] Digest: sha256:3f0e71eee1467ac6d0a16ea66da16e1e0092c56d7e06ebaf2695b5de175cd4d9
[10:59:39][Step 1/2] Status: Downloaded newer image for reg-hk.agodadev.io/library/node:14-slim
[10:59:53][Step 1/2] /usr/local/bin/codecoach -> /usr/local/lib/node_modules/codecoach/dist/app.js
[10:59:53][Step 1/2] + codecoach@1.5.2
[10:59:53][Step 1/2] added 83 packages from 50 contributors in 13.012s
[10:59:54][Step 1/2] error: MSBuildParser Error: log structure doesn't match {"log":"C:\\buildagent\\work\\1c22f4d3d9030336\\src\\Agoda.WebSite.MVC.Api\\Agoda.WebSite.MVC.Api.csproj : warning NU1701: Package 'Microsoft.AspNet.WebApi.Client 5.2.3' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project."}
[10:59:54][Step 1/2] error: Unexpected error MSBuildParser Error: log structure doesn't match {"stack":"Error: MSBuildParser Error: log structure doesn't match\n    at MSBuildParser.toLog (/usr/local/lib/node_modules/codecoach/dist/Parser/MSBuildParser.js:25:19)\n    at /usr/local/lib/node_modules/codecoach/dist/Parser/MSBuildParser.js:17:32\n    at Array.map (<anonymous>)\n    at MSBuildParser.parse (/usr/local/lib/node_modules/codecoach/dist/Parser/MSBuildParser.js:17:14)\n    at App.<anonymous> (/usr/local/lib/node_modules/codecoach/dist/app.js:60:31)\n    at Generator.next (<anonymous>)\n    at fulfilled (/usr/local/lib/node_modules/codecoach/dist/app.js:6:58)"}
[10:59:54][Step 1/2] error: Unexpected error {"error":{}}
[10:59:54][Step 1/2] Process exited with code 1
[10:59:54][Step 1/2] Process exited with code 1 (Step: Run (Command Line))
[10:59:54][Step 1/2] Step Run (Command Line) failed
[10:59:54]Step 2/2: Post check clean up (Cleanup docker data in Linux agent)
[10:59:54]Publishing internal artifacts (3s)
[10:59:54]Publishing artifacts (3s)
[10:59:58]Build finished
```

**Comment by yeeezsh** [comment]
artifacts with the password you will know

[HostManage_HostManage_-_CodeCoach_3571_artifacts.zip](https://github.com/codeleague/codecoach/files/7081184/HostManage_HostManage_-_CodeCoach_3571_artifacts.zip)
